Missing natives
I've done a clean installation on Debian and after running with gulp serve, got the following issue:

const types = internalBinding('types');
                      ^
ReferenceError: internalBinding is not defined

Problem fixed after adding "natives" to "devDependencies" of package.json